### ISSUE TITLE
spray-json, akka-http, slick shouldn't depend on instances

### ISSUE THREAD

**Issue by luksow** [theiterators/kebs#212]
spray-json, akka-http, slick modules depend on instances which is, in general, unnecessary, even though most users would probably add instances as a dep.

I think the correct solution would be to push `InstanceConverter` trait to macro-utils to sit there together with `CaseClass1Rep` or even better, create a thin module `core` or `base` and have `InstanceConverter` and `CaseClass1Rep` there.

**Comment by luksow** [comment]
In case https://github.com/theiterators/kebs/pull/214 is merged, play-json & circe should be fixed as well.

**Comment by pk044** [comment]
Done in https://github.com/theiterators/kebs/pull/269
