### ISSUE TITLE
`kebs-doobie` artifacts missing from Maven Central Repository

### ISSUE THREAD

**Issue by brendanmaguire** [theiterators/kebs#223]
Firstly thanks for the great library! :slightly_smiling_face: 

I cannot add `kebs-doobie` to my project and it [appears to be missing from Maven](https://search.maven.org/search?q=g:pl.iterators%20doobie). Is this expected?

**Comment by pk044** [comment]
@brendanmaguire we haven't made a full release yet. If you want to test it, there should be a snapshot version available on Sonatype: `1.9.5-SNAPSHOT` I believe 😃

**Comment by brendanmaguire** [comment]
Thanks @pk044 . Tested and works well locally :slightly_smiling_face: When there's a full release I'll add it to our builds.

**Comment by brendanmaguire** [comment]
@pk044 , I am wondering if you know when `0.9.5` might be released?

**Comment by pk044** [comment]
@brendanmaguire I tried to release today but publishing to Sonatype is failing. I'll try to fix it this week and release the library.

**Comment by pk044** [comment]
@brendanmaguire I just released it. new release should be available on Maven Central in several hours (indexing on MC can take a while). 
https://github.com/theiterators/kebs/releases/tag/v1.9.5

**Comment by brendanmaguire** [comment]
Great! :rocket: Thanks @pk044
