### ISSUE TITLE
Add support for Scala.js

### ISSUE THREAD

**Issue by pk044** [theiterators/kebs#254]
Using this SBT plugin is recommended: https://github.com/sbt/sbt-projectmatrix

**Comment by pk044** [comment]
Scala.js support for `macroUtils`, `tagged` and `opaque` modules was added in #259. Other modules can only be migrated after #212 is done - see https://github.com/theiterators/kebs/pull/259#pullrequestreview-1209892280.

**Comment by luksow** [comment]
This was solved in https://github.com/theiterators/kebs/pull/389
