### ISSUE TITLE
Provide mappings for all standard Java types

### ISSUE THREAD

**Issue by luksow** [theiterators/kebs#26]
It's very common that you paste mappers for types like `ZonedDateTime`, `UUID` or `Currency` from project to project. It'd be nice to have those covered for kebs.

It might be done with typeclasses like `Reads`, `Writes` and `CaseClass1Rep` (or variant). This will allow us to easily write unmarshallers for Akka HTTP matchers and such.

User-facing data, like JSON or PathMatchers need special handling as throwing Exception is not the best idea ex. for `spray-json`.

**Comment by jborkowski** [comment]
Can I take this one?

**Comment by luksow** [comment]
@jborkowski sure. Two things you should discuss with me / @marcin-rzeznicki are:

1. What typeclass to use and if it's CaseClass1Rep maybe it's a good time to make it more standalone from macros.
2. List of types you'd like to cover.

**Comment by marcin-rzeznicki** [comment]
`CaseClass1Rep` as such is independent of macros. Macros are just one way of obtaining an instance of it.

**Comment by marcin-rzeznicki** [comment]
So, you can freely provide `CaseClass1Rep` for anything you want. The machinery should work. In fact, macros will *not* try to provide an instance of `Rep` for any Java type and bail out early. For the list of types you want to support you should probably go through some projects you're working on (or know about) and see what are the commonly hand-writted implicits that conform to this model.
