### ISSUE TITLE
Scala 2.11 version of kebs-avro is not available for the latest versions

### ISSUE THREAD

**Issue by ylabi** [theiterators/kebs#32]
Is scala 2.11 still supported ? If yes, builds for it do not seem to be available in maven (for version greater 1.5.0 that is) :
https://mvnrepository.com/artifact/pl.iterators/kebs-avro

**Comment by marcin-rzeznicki** [comment]
Hey, thanks for reporting.
It should be - I guess it is a bug in `sbt-release` plugin (or sbt aggregation - possibly https://github.com/sbt/sbt/issues/3698 ), which prevents it from being published. I'll try to fix this. Thanks again.

**Comment by marcin-rzeznicki** [comment]
I was able to fix publishing for 2.11.x . These cross builds are available again starting with version 1.6.1. Thanks again for letting me know.
