### ISSUE TITLE
Release for Scala 2.13.0 wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [theiterators/kebs#42]

**Comment by marcin-rzeznicki** [comment]
Good idea!

**Comment by plokhotnyuk** [comment]
Please, consider partial release for Scala 2.13 at least for `spray-json` and `play-json` modules...

**Comment by marcin-rzeznicki** [comment]
For tracking - we still do not have `slick_pg` and `avro` published for 2.13 
https://github.com/tminglei/slick-pg/issues/453 . We can partially publish though :+1:

**Comment by plokhotnyuk** [comment]
Still there are no any sub-directory for 2.13: https://repo1.maven.org/maven2/pl/iterators/

**Comment by plokhotnyuk** [comment]
up

**Comment by plokhotnyuk** [comment]
@jborkowski Great work! Thank you so much!
