### ISSUE TITLE
Spray-json None values are always converted to null. How to change this?

### ISSUE THREAD

**Issue by myDisconnect** [theiterators/kebs#73]
Spray converts `None` values to `null` only when NullOptions trait is added but by default it doesn't add those fields to JSON.
When using kebs implicitly[RootJsonFormat[xxx]], it converts `None` values to `null`.  Example of such case: https://scastie.scala-lang.org/myDisconnect/tgnMaqh4QcCdQWDBWQZT5A/7 see f4 field (this is also visible in Kebs tests)
Is it possible to change this behaviour in Kebs and ignore None values?

Note: This seems to be happening when a case class has more than 22 parameters

**Comment by myDisconnect** [comment]
Hey @luksow, I updated the issue description and added a sample, I don't think it's related to Spray

**Comment by luksow** [comment]
Thanks for detailed report. I've found out why. It's a bug and we'll try to fix it.

**Comment by myDisconnect** [comment]
🥳 When will the new version will be released?

**Comment by pk044** [comment]
@myDisconnect We will try to get it released this week.

**Comment by pk044** [comment]
@myDisconnect FYI: the new release is already available on Maven Central
