### ISSUE TITLE
Slick - Support for case classes with more than 22 fields 

### ISSUE THREAD

**Issue by dbronecki** [theiterators/kebs#8]
It would be nice if Kebs would provide Slick mappers for case classes with more than 22 fields.

**Comment by bartekkalinka** [comment]
Shouldn't this issue be closed as it is resolve with [this PR](https://github.com/theiterators/kebs/pull/12)?

**Comment by dbronecki** [comment]
It's supported directly in Slick (https://scala-slick.org/doc/3.3.3/cookbook.html#mapping-more-than-22-fields)
